config/routes.rb
Rails.application.routes.draw do
  root 'farms#index'
  devise_for :users
  resources :farms, only: [:index, :show]
  resources :users do
    resources :farms
  end
  resources :farms do
    resources :products
  end
  resources :farms do
    resources :markets
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :farm

  validates :item, presence: true
  validates :quantity, length: { maximum: 15 }
  validates :price, numericality: true
  validates :price, length: { maximum: 5 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @farm = Farm.find(params[:id])
    @products = @farm.products
  end

  def new
    @farm = Farm.find(params[:farm_id])
    @product = Product.new
    @user = current_user
  end

  def create
    @user = current_user
    if @user.farmer? == true
      @farm = @user.farm
      @product = Product.new(product_params)
      if @product.save
        flash[:notice] = "Product added!"
        redirect_to user_farm_path(@user, @farm)
      else
        flash[:errors] = @product.errors.full_messages.join(', ')
        render :new
      end
    end
  end

  def edit
    @farm = Farm.find(params[:id])
    @user = current_user
    @products = @farm.products
    @product = Product.find(params[:id])
  end

  def update
    @farm = Farm.find(params[:id])
    @user = current_user
    @products = @farm.products
    @product = Product.find(params[:id])
    if @farm.user != @user
      flash[:notice] = "You don't have permission to edit this!"
      redirect_to :root_path
    end
    if @product.update(product_params)
      flash[:notice] = "Successfully updated"
      redirect_to farm_path(@farm)
    else
      flash[:errors] = @product.errors.full_messages.join(', ')
      render :new
    end
  end

    def destroy
      @farm = Farm.find(params[:id])
      @user = current_user
      @product = Product.find(params[:id])
      if @farm.user != @user
        flash[:notice] = "You don't have permission to delete this!"
        redirect_to :root_path
      end
      if @product.destroy
        flash[:notice] = "#{@product.item} deleted"
        redirect_to farm_path(@farm)
      end
    end

private

  def product_params
    params.require(:product).permit(
    :item,
    :quantity,
    :price,
    :expiration
    ).merge(farm_id: @farm.id)
  end

end

app/views/products/new.html.erb
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>
<div class="registration-form small-10 medium-8 large-6 centered columns">
  <h3>What's in season?</h3>

  <%= form_for [@farm, @product], url: farm_products_path(@farm) do |f| %>
    <div class="field column small-12">
      <% f.label :item, class: "text-input-label" %><br>
      <%= f.text_field :item, class: "text-input-field", placeholder: "Product Name", autofocus: true %>
    </div>
    <div class="field column small-12">
      <% f.label :price, class: "text-input-label" %><br>
      <%= f.text_field :price, class: "text-input-field", placeholder: "price (like this: 12.75)"%>
    </div>
    <div class="field column small-12">
      <% f.label :quantity, class: "text-input-label" %><br>
      <%= f.text_field :quantity, class: "text-input-field", placeholder: "listed price is per how much of this product?" %>
    </div>
    <div class="field column small-12">
      <% f.label :expiration, class: "text-input-label" %><br>
      <%= f.text_field :expiration, class: "text-input-field", placeholder: "Expiration - This will be available until when? " %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "Add item", class: "registration-form button  round medium" %>
    </div>
  <% end %>
</div>
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>