config/routes.rb
Rails.application.routes.draw do
  root 'farms#index'
  devise_for :users
  resources :farms, only: [:index, :show]
  resources :users do
    resources :farms
  end
  resources :farms do
    resources :products
  end
  resources :farms do
    resources :markets
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <% google_key = ENV["GOOGLE_MAPS_API_KEY"] %>
    <script
      src="https://maps.googleapis.com/maps/api/js?key=#{google_key}">
    </script>
    <title><%= content_for?(:title) ? yield(:title) : "Farm to Foodie" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body style="background-image:url(http://i.imgur.com/IUVUIq4.jpg)">

    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Farm To Foodie</a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <%- if user_signed_in? -%>
            <% if @user.farmer? %>
              <% if @user.farm.nil? %>
                <li><%= link_to 'List My Farm', new_user_farm_path(@user) %></li>
              <% else %>
                <li><%= link_to "My Farm", user_farm_path(@user.id, @user.farm.id) %></li>
              <% end %>
          <% end %>

            <li><%= link_to 'Update my Info', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <%- else -%>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <%- end -%>
        </ul>
      </section>
    </nav>
    <div class="registration-form">
      <%- flash.each do |key, value| -%>
        <div class="flash flash-<%= key %>">
          <h3><%= value %></h3>
        </div>
      <%- end -%>
    </div>

    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= yield :extra_footer %>
  </body>
</html>